name: Schedule Friday 0700

on:
  schedule:
    - cron: '0 7 * * 5'
  issue_comment:
    types: [created]

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        env:
          IN_PROGRESS_COLUMN_ID: ${{ secrets.IN_PROGRESS_COLUMN_ID }}
        with:
          script: |
            const columnId = 19495457;
            const script = require('./github-actions/trigger-schedule/add-update-label-weekly/add-label.js');
            script({ g: github, c: context }, columnId)
